# Generated by Django 4.2.5 on 2023-09-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=20)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('estadoL', models.CharField(blank=True, choices=[('pago', 'Pago'), ('sin pagar', 'Sin pagar')], max_length=10, null=True)),
            ],
        ),
    ]
