# Generated by Django 4.2.5 on 2023-09-10 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0002_conductor_vehiculo'),
        ('liquidacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conductor.conductor'),
        ),
    ]
