# Generated by Django 4.2.1 on 2023-07-01 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('estadoL', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Liquidacion.estadol')),
            ],
        ),
    ]
