# Generated by Django 4.2.2 on 2023-06-22 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LiquidacionConductor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='estadoC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LiquidacionConductor.estadoc'),
        ),
    ]
