# Generated by Django 4.2.5 on 2023-09-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('estadoC', models.CharField(blank=True, choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=10, null=True)),
            ],
        ),
    ]
