# Generated by Django 4.2.5 on 2023-09-10 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
        ('conductor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo'),
        ),
    ]
